Purpose: visualize SEM pore size analysis

# Import libraries
library(ggplot2)
library(ggprism)
library(ggbeeswarm)
library(dplyr)

# Import dataset
df <- read.csv("2024.02.06_sem_total_analysis.csv")

# Run statistical analysis
aov.results <- aov(Feret ~ Condition, df)
summary(aov.results)

# Visualize
pdf("2024.02.07_sem_pore_analysis.pdf", width = 4, height = 4)
ggplot(df, aes(x = Condition, y = Feret)) +
  stat_summary(fun.y = mean, fun.ymin = mean, fun.ymax = mean, 
               geom = 'crossbar', width = 0.4) +
  geom_quasirandom(size = 4, color = 'black') +
  geom_quasirandom(size = 3, aes(color = Condition)) +
  scale_color_manual(values = c('darkturquoise','turquoise','goldenrod','gold')) +
  ylab('Mean Feret Diameter \n (microns)') +
  xlab('') +
  theme_prism() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  scale_x_discrete(labels = c(bquote(GelMA^HC), bquote(GelMA^LC), bquote(GelMA-Cad^HC), bquote(GelMA-Cad^LC))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  theme(legend.position = 'none') +
  ylim(c(0,60))
