Purpose: visualize atomic force microscopy measurements

# Import libraries
library(ggplot2)
library(ggprism)
library(ggbeeswarm)

# Import data
df <- read.csv("2024.02.05_AFM_compiled_data.csv")

# Statistical analysis, one way ANOVA
aov.results <- aov(Average.Young.s.Modulus..kPa. ~ Condition, df)
summary(aov.results)

tukey <- TukeyHSD(aov.results)
print(tukey)

# Visualize
pdf("2024.02.07_AFM_analysis.pdf", width = 4, height = 4)
ggplot(df, aes(x = Condition, y = Average.Young.s.Modulus..kPa.)) +
  stat_summary(fun.y = mean, fun.ymin = mean, fun.ymax = mean, 
               geom = 'crossbar', width = 0.4) +
  geom_quasirandom(size = 4, color = 'black') +
  geom_quasirandom(size = 3, aes(color = Condition)) +
  scale_color_manual(values = c('darkturquoise','turquoise','goldenrod','gold','salmon')) +
  ylab('Young\'s Modulus (kPa)') +
  xlab('') +
  theme_prism() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  scale_x_discrete(labels = c(bquote(GelMA^HC), bquote(GelMA^LC), bquote(GelMA-Cad^HC), bquote(GelMA-Cad^LC))) +
  theme(legend.position = 'none')
