Purpose: visualize average storage and loss moduli from rheological characterization

# Import libraries
library(ggplot2)
library(ggprism)
library(ggbeeswarm)

# Import data
df <- read.csv("2024.04.04_compiled_rheology_averages.csv")

# Add sample details
df$peptide <- c('-','-','-','+','+','+','+','-','+','+','-','-','-','+','+','-','-','-','+','+')
df$stiffness <- c('HC','HC','HC','HC','LC','LC','LC','LC','HC','HC','LC','LC','LC','LC','HC','LC','HC','HC','HC','LC')

# Statistical analysis, one way ANOVA
aov.results <- aov(Average.Loss.Modulus ~ peptide + stiffness, df)
summary(aov.results)

tukey <- TukeyHSD(aov.results)
print(tukey)

# Statistical analysis, one way ANOVA
aov.results <- aov(Average.Storage.Modulus ~ peptide + stiffness, df)
summary(aov.results)

tukey <- TukeyHSD(aov.results)
print(tukey)

# Visualize
pdf("2024.05.27_rheology_analysis.pdf", width = 4, height = 4)
ggplot(df, aes(x = Condition, y = Average.Storage.Modulus)) +
  stat_summary(fun.y = mean, fun.ymin = mean, fun.ymax = mean, 
               geom = 'crossbar', width = 0.4) +
  geom_quasirandom(size = 4, color = 'black') +
  geom_quasirandom(size = 3, aes(color = Condition)) +
  scale_color_manual(values = c('turquoise','darkturquoise','gold','goldenrod','salmon')) +
  ylab('Average \n Storage Modulus (Pa)') +
  xlab('') +
  theme_prism() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  scale_x_discrete(labels = c(bquote(GelMA^HC), bquote(GelMA^LC), bquote(GelMA-Cad^HC), bquote(GelMA-Cad^LC))) +
  theme(legend.position = 'none')

ggplot(df, aes(x = Condition, y = Average.Loss.Modulus)) +
  stat_summary(fun.y = mean, fun.ymin = mean, fun.ymax = mean, 
               geom = 'crossbar', width = 0.4) +
  geom_quasirandom(size = 4, color = 'black') +
  geom_quasirandom(size = 3, aes(color = Condition)) +
  scale_color_manual(values = c('turquoise','darkturquoise','gold','goldenrod','salmon')) +
  ylab('Average \n Loss Modulus (Pa)') +
  xlab('') +
  theme_prism() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  scale_x_discrete(labels = c(bquote(GelMA^HC), bquote(GelMA^LC), bquote(GelMA-Cad^HC), bquote(GelMA-Cad^LC))) +
  theme(legend.position = 'none')
